# Generated by Django 3.2.19 on 2024-05-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRooms',
            fields=[
                ('roomCode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('roomName', models.CharField(default='', max_length=100, unique=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
