# Generated by Django 3.2.19 on 2024-05-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
